spring:
   jmx:
      enabled: false
   application:
     name: Lego Bricklink Inventory Synchronizer
   datasource:
      url: jdbc:mysql://shared50.accountservergroup.com:3306/a925261_dev_lego
      username: xxxxxxxxxxxxxxxxxxxxxxxxxx
      password: xxxxxxxxxxxxxxxxxxxxxxxxxx
      #driver-class-name: com.mysql.jdbc.Driver
      hikari:
         connection-timeout: 60000
         idle-timeout: 1800000
         minimum-idle: 10
         maximum-pool-size: 30

logging:
   level:
      root: INFO
      com.vattima.lego.data.ibatis.mapper: WARN
      org.mybatis: WARN
      com.gargoylesoftware: ERROR
      com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter: OFF
      com.zaxxer: WARN
      feign: DEBUG

bricklink:
   rest:
      client-config-dir: C:\Users\tvatt\.credentials\bricklink
      client-config-file: bricklink-client-api-keys.json
   web:
      client-config-dir: C:\Users\tvatt\.credentials\bricklink
      client-config-file: bricklink-web.json
      pool:
         default-max-per-route: 20
         max-per-route: 20
         max-total: 50

lego:
   sheet:
      dataStoreDir: c:/users/tvatt/.credentials/sheets.googleapis.com-java-quickstart
      clientSecretDir: /client_secret.json
      id: 1KegFWxww3v6qWn6lfg8PWb-X8Ipc8Y3Asq7l6subgq4
      workbook: By BOX
      #workbook: By BOX, by NUMBER
      range: A2:F

mybatis:
   type-aliases-package: com.vattima.lego.data.ibatis.type.aliases
   type-handlers-package: com.vattima.lego.data.ibatis.type.handler
   configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 1000
      default-statement-timeout: 30
      lazy-loading-enabled: true
   mapper-locations: com/vattima/lego/data/ibatis/*

debug: false
